# SPDX-License-Identifier: BSD-3-Clause
---
# handlers file for letsencrypt_ca
- name: update bundles
  command: "{{letsencrypt_ca_update_command}}"
- name: restart sssd
  service:
    name: sssd
    state: restarted
